# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:        ROLE_VISITEUR
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_EXTRA_ADMIN: ROLE_SUPER_ADMIN
 
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false    
        main:
            pattern: ^/
            #user_checker: fos_user.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # the user is redirected here when they need to log in
                #login_path: /login

                # if true, forward the user to the login form instead of redirecting
                #use_forward: false
                success_handler: redirect.after.login
                login_path: fos_user_security_login

                check_path: fos_user_security_check

                default_target_path: /login
                always_use_default_target_path: false

            logout:
                path:   /logout
                target: /user/home      
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/user/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/user/, role: ROLE_USER }
       
        
        
